Create memo app
ryufuta/sinatra-memo-app pull request #1
Opened 2024-04-22 07:03 UTC by ryufuta

2024-04-28 15:23 UTC, u1tnk requested changes

2024-04-28 15:23 UTC, u1tnk commented on .gitignore
> +*.gem
こちらは必要なものだけにしましょう。
意図せずにignoreされて混乱したりします。

2024-04-28 15:23 UTC, u1tnk commented on app.rb
> +  def hattr(text)
hと同じ内容に見えますが、これは何のためでしょうか？

2024-04-28 15:23 UTC, u1tnk commented on memos.csv
> +aa26821d-27c1-4a7a-92e5-ef82570097d0,メモ1,メモ1の内容
これはデータなのでコミットせずに .gitignoreに入れるようにしましょう

2024-04-30 08:38 UTC, ryufuta commented on app.rb
> +  def hattr(text)
https://sinatrarb.com/faq.html#escape_html
を参考にしたのですが、私の勘違いであり、不要なので削除しました。

> And you can escape text inside element attributes in your templates like this

とあるので`edit.erb`の`<input type="text" name="title" value="<%== @memo[:title] %>">`で必要と思っていたのですが、hattrはHTMLではなくURIをエスケープするためのメソッドなので今回のアプリ内では使用箇所がありませんでした。
そもそも使用するとしても`<%== @memo[:title] %>`ではなく`<%= hattr @memo[:title] %>`とする必要があるので二重に間違っていました。

2024-04-30 16:21 UTC, u1tnk approved these changes

2024-05-01 02:53 UTC, merged